### ISSUE TITLE
Shell > Trying on postgres but always resolving to localhost

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler-Shell#13]
When running the following command in shell :

```
connect -server postgresql -database dpmmc -user dpmmc_read
-password XXXXX -host svq-postgres0.site-mairie.noumea.nc
```

I get the following output from the  `stacktrace` command :

```
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2385)
```

as if the `-host` parameter was not taken in account. Any idea what I'm doing wrong ?

**Comment by sualeh** [comment]
@adriens - please run this command again, and then run the `stacktrace` command. Please send me the stack trace.

**Comment by adriens** [comment]
```
schemacrawler> connect -server postgresql -database dpmmc -user dpmmc_read -password XXXXX -host svq-postgres0.site-mairie.noumea.nc
Cannot connect to database
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
schemacrawler> stacktrace 
java.lang.RuntimeException: Cannot connect to database
	at schemacrawler.shell.commands.ConnectCommands.connect(ConnectCommands.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at org.springframework.shell.Shell.evaluate(Shell.java:180)
	at org.springframework.shell.Shell.run(Shell.java:142)
	at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:723)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at schemacrawler.shell.SchemaCrawlerShellApplication.main(SchemaCrawlerShellApplication.java:46)
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2385)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2110)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1563)
	at schemacrawler.shell.commands.ConnectCommands.loadSchemaRetrievalOptionsBuilder(ConnectCommands.java:236)
	at schemacrawler.shell.commands.ConnectCommands.connect(ConnectCommands.java:117)
	... 15 more
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.connect(Driver.java:256)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:53)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:291)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2395)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2381)
	... 19 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:70)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	... 27 more
schemacrawler> 
```

**Comment by adriens** [comment]
Loks like `host` is not taken in account.. hence switching to `localhost`

**Comment by sualeh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix issue with host in SchemaCrawler shell](https://trello.com/c/K22z6bY4/396-fix-issue-with-host-in-schemacrawler-shell)
